title: open-devsecops2
description: 'From Classroom to Industry: Bridging the DevSecOps Knowledge Gap with Open, Practical Learning.'
remote_theme: just-the-docs/just-the-docs

logo: "/assets/images/opendevsecops-transparent.png"
favicon_ico: "/assets/images/opendevsecops-favicon.ico"

url: https://open-devsecops2.github.io
search_enabled: true
search:
  button: true

aux_links:
  Github: https://github.com/open-devsecops
  Contribute: https://github.com/open-devsecops/open-devsecops.github.io

callouts:
  important:
    title: Important
    color: green
  warning:
    title: Warning
    color: yellow
  info:
    title: Info
    color: blue
  lab:
    title: Access The Lab
    color: purple